Logger class
St0rmPetrel/webserv pull request #4
Opened 2022-02-25 19:03 UTC by Nanatysy

2022-02-26 08:17 UTC, St0rmPetrel requested changes
Кроме замечаний в коде, у тебя не проходят тесты, и ты забыла слилться с новыми изменениями по Makefile c Анастасией.

2022-02-27 06:27 UTC, St0rmPetrel commented
> 

Тесты не компилятся, там не только в дифе проблема. В этом тесте можно вообще убрать diff и выводить результат теста в консоль. Еще было бы круто настраивать вывод времени (есть/нет) или при выводе в ostream не пивать время, а при выводе в файл писать, как с цветами ты тут сделала (Это только как предложение к улучшению, можно оставить как есть, уже оч круто получилось). Еще (тут может я не прав), можно создать только один стрим - fstream, и если надо писать например в stdout, то в качестве файла указывать /dev/stdout - это упростит конфигурацию и логику кода.

2022-03-03 15:05 UTC, St0rmPetrel requested changes

2022-03-03 15:05 UTC, St0rmPetrel commented on srcs/logger/Options.hpp
> +		bool			bfile_output;
Может убрать это из опций, и сделаем приватные поля в классе логгер и будем из заполнять в конструкторе и функции set_up. Потому что по факту это уже не опции, а внутренняя логика

2022-03-03 15:20 UTC, St0rmPetrel requested changes

2022-03-03 15:20 UTC, St0rmPetrel commented on srcs/logger/Logger.hpp
>  			ILogger& with_field(const std::string& key, const std::string& value);
Давай ее вообще уберём, не понятно как делать красиво

2022-03-20 15:14 UTC, St0rmPetrel approved these changes

2022-03-27 18:49 UTC, Moishilop approved these changes

2022-03-27 19:42 UTC, merged